### PR TITLE
Support specifying number of iterations for map2alm

### PR DESCRIPTION
**Pull request by zonca**
If 0, it uses the standard map2alm

### CODE REVIEW

**Comment by yaojian95** [comment]
Hi, Zonca, are you modifying the pysm and healpy at the same time? Because when I try to use the pysm3.apply_smoothing_and_coord_transform function in the laster version of pysm3 (3.4.0b5), it has the 'AttributeError: module 'healpy' has no attribute 'map2alm_lsq'' for the healpy at version 1.15.0. After I upgrade the healpy to 1.16.2, the new version of pysm3 works well. 

Just to remind you of this potential version conflict.

**Comment by zonca** [comment]
@yaojian95 thank you very much for reporting this!
you are right, I need to add the requirement of  healpy 1.60.0
